### ISSUE TITLE
Cannot execute test with agent Spock

### ISSUE THREAD

**Issue by dtanedo** [reportportal/agent-java-spock#14]
Hi,

Gradle is throwing a URL Class Loader error when executing test with the latest agent version.

```14:30:31.562 [DEBUG] [TestEventLogger] com.sampleorg.sampleproject > initializationError FAILED
14:30:31.562 [DEBUG] [TestEventLogger]     java.lang.NoClassDefFoundError: rp/com/google/common/base/Supplier
14:30:31.562 [DEBUG] [TestEventLogger]         at com.epam.reportportal.spock.ReportPortalSpockExtension.<init>(ReportPortalSpockExtension.java:34)
14:30:31.562 [DEBUG] [TestEventLogger]         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
14:30:31.562 [DEBUG] [TestEventLogger]         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
14:30:31.562 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
14:30:31.562 [DEBUG] [TestEventLogger]         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
14:30:31.562 [DEBUG] [TestEventLogger]         at java.lang.Class.newInstance(Class.java:442)
14:30:31.562 [DEBUG] [TestEventLogger]         at org.spockframework.runtime.GlobalExtensionRegistry.instantiateGlobalExtension(GlobalExtensionRegistry.java:88)
14:30:31.562 [DEBUG] [TestEventLogger]         at org.spockframework.runtime.GlobalExtensionRegistry.initializeGlobalExtensions(GlobalExtensionRegistry.java:58)
14:30:31.562 [DEBUG] [TestEventLogger]         at org.spockframework.runtime.RunContext.start(RunContext.java:56)
14:30:31.562 [DEBUG] [TestEventLogger]         at org.spockframework.runtime.RunContext.get(RunContext.java:166)
14:30:31.562 [DEBUG] [TestEventLogger]         at org.spockframework.runtime.Sputnik.runExtensionsIfNecessary(Sputnik.java:90)
14:30:31.562 [DEBUG] [TestEventLogger]         at org.spockframework.runtime.Sputnik.getDescription(Sputnik.java:54)
14:30:31.562 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:85)
14:30:31.562 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
14:30:31.562 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
14:30:31.562 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
14:30:31.562 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
14:30:31.562 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:30:31.562 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:30:31.562 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:30:31.562 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:498)
14:30:31.562 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
14:30:31.562 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
14:30:31.562 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
14:30:31.562 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
14:30:31.562 [DEBUG] [TestEventLogger]         at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
14:30:31.562 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:117)
14:30:31.562 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:30:31.562 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:30:31.562 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:30:31.562 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:498)
14:30:31.562 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
14:30:31.562 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
14:30:31.562 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
14:30:31.562 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
14:30:31.562 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
14:30:31.562 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
14:30:31.562 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
14:30:31.562 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
14:30:31.562 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
14:30:31.562 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
14:30:31.562 [DEBUG] [TestEventLogger]         at java.lang.Thread.run(Thread.java:748)
14:30:31.562 [DEBUG] [TestEventLogger] 
14:30:31.562 [DEBUG] [TestEventLogger]         Caused by:
14:30:31.562 [DEBUG] [TestEventLogger]         java.lang.ClassNotFoundException: rp.com.google.common.base.Supplier
14:30:31.562 [DEBUG] [TestEventLogger]             at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
14:30:31.562 [DEBUG] [TestEventLogger]             at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
14:30:31.562 [DEBUG] [TestEventLogger]             at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
14:30:31.562 [DEBUG] [TestEventLogger]             at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
14:30:31.562 [DEBUG] [TestEventLogger]             ... 42 more
14:30:31.564 [DEBUG] [TestEventLogger] 
```

I'm using Oracle JDK 1.8.202 with Gradle version: 
```
------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_202 (Oracle Corporation 25.202-b08)
OS:           Mac OS X 10.13.6 x86_64
```

**Comment by dtanedo** [comment]
Hi,

I found out that the jar of agent-java-spock is not a **fatJar**. I added the other dependencies found
in the build.gradle of the agent-java-spock project. 

```
dependencies {
        testImplementation 'com.epam.reportportal:commons-model:4.2.0'
        testImplementation 'com.epam.reportportal:client-java:4.0.10'
        testImplementation 'com.epam.reportportal:agent-java-spock:3.0.0'
}
```

You may need to probably rebuild the project to add the dependencies to the uploaded artifact to the
maven repository.
