### ISSUE TITLE
reprotal portal initializationError with Spock

### ISSUE THREAD

**Issue by keilwill** [reportportal/agent-java-spock#16]
Im trying to use Report Portal with Spock-core:1.3-groovy-2.5 and geb 3.4, but get this error

22:43:36.970 INFO  c.e.r.s.ReportPortalSpockExtension - Test worker - "LAUNCHING" the test run

com.epam.reportportal.utils.properties.PropertiesLoader.load()Lcom/epam/reportportal/utils/properties/PropertiesLoader;
java.lang.NoSuchMethodError: com.epam.reportportal.utils.properties.PropertiesLoader.load()Lcom/epam/reportportal/utils/properties/PropertiesLoader;
	at com.epam.reportportal.service.ReportPortal$Builder.defaultPropertiesLoader(ReportPortal.java:539)
	at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:400)
	at com.epam.reportportal.spock.SpockService$1.get(SpockService.java:73)
	at com.epam.reportportal.spock.SpockService$1.get(SpockService.java:68)
	at com.epam.reportportal.spock.SpockService$MemoizingSupplier.get(SpockService.java:540)
	at com.epam.reportportal.spock.SpockService.startLaunch(SpockService.java:105)
	at com.epam.reportportal.spock.ReportPortalSpockExtension.start(ReportPortalSpockExtension.java:40)
	at org.spockframework.runtime.GlobalExtensionRegistry.startGlobalExtensions(GlobalExtensionRegistry.java:106)
	at org.spockframework.runtime.RunContext.start(RunContext.java:63)
	at org.spockframework.runtime.RunContext.get(RunContext.java:166)
	at org.spockframework.runtime.Sputnik.runExtensionsIfNecessary(Sputnik.java:90)
	at org.spockframework.runtime.Sputnik.getDescription(Sputnik.java:54)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:89)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)

GebishOrgSpec > initializationError FAILED
    java.lang.NoSuchMethodError: com.epam.reportportal.utils.properties.PropertiesLoader.load()Lcom/epam/reportportal/utils/properties/PropertiesLoader;
22:43:36.988 INFO  c.e.r.s.ReportPortalSpockExtension - org.spockframework.runtime.RunContext.stop() - "LAUNCH" completed
Exception in thread "org.spockframework.runtime.RunContext.stop()" java.lang.NoSuchMethodError: com.epam.reportportal.utils.properties.PropertiesLoader.load()Lcom/epam/reportportal/utils/properties/PropertiesLoader;
	at com.epam.reportportal.service.ReportPortal$Builder.defaultPropertiesLoader(ReportPortal.java:539)
	at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:400)
	at com.epam.reportportal.spock.SpockService$1.get(SpockService.java:73)
	at com.epam.reportportal.spock.SpockService$1.get(SpockService.java:68)
	at com.epam.reportportal.spock.SpockService$MemoizingSupplier.get(SpockService.java:540)
	at com.epam.reportportal.spock.SpockService.finishLaunch(SpockService.java:323)
	at com.epam.reportportal.spock.ReportPortalSpockExtension.stop(ReportPortalSpockExtension.java:54)
	at org.spockframework.runtime.GlobalExtensionRegistry.stopGlobalExtensions(GlobalExtensionRegistry.java:112)
	at org.spockframework.runtime.RunContext.stop(RunContext.java:67)
	at org.spockframework.runtime.RunContext.access$000(RunContext.java:29)
	at org.spockframework.runtime.RunContext$2.run(RunContext.java:160)

**Comment by HardNorth** [comment]
Please use the latest version of the agent, currently: https://github.com/reportportal/agent-java-spock/releases/tag/5.1.0-BETA-1
