### ISSUE TITLE
NullPointerException when data value has null value

### ISSUE THREAD

**Issue by pushkar-nayama** [reportportal/agent-java-spock#26]
Hi,

When data value in the data table contains value as **null** then getting **_NullPointerException in class NodeInfoUtils in method unrollIterationDescription at line number 131_**. Because we are getting data value as **dataValues[i].toString()**

**Please find below Environment details, what I am using**:
Java: 1.8.0_181
agent-java-spock: 5.1.0-RC-1
logger-java-log4j: 5.0.3
commons-model: 5.3.3
client-java: 5.1.0-RC-12
spock version: 1.3-groovy-2.5
groovy version: 2.5.0

**Example to reproduce the issue**:
@Unroll
def "print value as #value and length as #length"(def value, int length) {
    expect:
    println("$value and $length")

    where:
    value    | length
    "Spock"  | 5
    null     | 4
}

**Exception while running second iteration**:

java.lang.NullPointerException
	at com.epam.reportportal.spock.ReportPortalSpockListener.reportError(ReportPortalSpockListener.java:319)
	at com.epam.reportportal.spock.ReportPortalSpockListener.error(ReportPortalSpockListener.java:507)
	at org.spockframework.runtime.MasterRunListener.error(MasterRunListener.java:71)
	at org.spockframework.runtime.JUnitSupervisor.error(JUnitSupervisor.java:101)
	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:486)
	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:467)
	at org.spockframework.runtime.BaseSpecRunner.runSpec(BaseSpecRunner.java:73)
	at org.spockframework.runtime.BaseSpecRunner.run(BaseSpecRunner.java:64)
	at org.spockframework.runtime.Sputnik.run(Sputnik.java:63)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	

**Please find below screenshot for more details**:
![image](https://user-images.githubusercontent.com/43025030/139576202-904a8c50-91f6-41d8-a056-940a4ee17132.png)

![image](https://user-images.githubusercontent.com/43025030/139576205-adf6df79-6762-4cce-b9f8-0766aef85375.png)

**Comment by pushkar-nayama** [comment]
Raised pull request https://github.com/reportportal/agent-java-spock/pull/27 for this issue.

**Comment by HardNorth** [comment]
Fixed in: https://github.com/reportportal/agent-java-spock/releases/tag/5.1.0-RC-3

Had to update many method names to unify with other agents, sorry.
