### ISSUE TITLE
Got "Error Type: LAUNCH_NOT_FOUND" when run test

### ISSUE THREAD

**Issue by greenleaves1** [reportportal/agent-java-spock#5]
```properties
rp.endpoint = http://localhost:8080
rp.uuid = f9660bb3-89b3-4a4a-adfa-df8ba0c480bb
rp.launch = superadmin_TEST1
rp.project = superadmin_personal
```

gradle dependency:
`testCompile 'com.epam.reportportal:agent-java-spock:2.6.0'`

`gradle test`

```
Exception in thread "org.spockframework.runtime.RunContext.stop()" com.epam.reportportal.exception.ReportPortalClientException: Report Portal returned error
Status code: 404
Status message: Not Found
Error Message: Launch 'null' not found. Did you use correct Launch ID?
Error Type: LAUNCH_NOT_FOUND
Stack Trace: 
        at com.epam.reportportal.service.ReportPortalErrorHandler.handleClientError(ReportPortalErrorHandler.java:47)
        at com.epam.reportportal.restclient.endpoint.DefaultErrorHandler.handle(DefaultErrorHandler.java:73)
        at com.epam.reportportal.restclient.endpoint.DefaultErrorHandler.handle(DefaultErrorHandler.java:40)
        at com.epam.reportportal.restclient.endpoint.HttpClientRestEndpoint.executeInternal(HttpClientRestEndpoint.java:341)
        at com.epam.reportportal.restclient.endpoint.HttpClientRestEndpoint.put(HttpClientRestEndpoint.java:178)
        at com.epam.reportportal.service.ReportPortalService.finishLaunch(ReportPortalService.java:103)
        at com.epam.reportportal.spock.SpockReporter.finishLaunch(SpockReporter.java:300)
        at com.epam.reportportal.spock.ReportPortalSpockExtension.stop(ReportPortalSpockExtension.java:54)
        at org.spockframework.runtime.GlobalExtensionRegistry.stopGlobalExtensions(GlobalExtensionRegistry.java:111)
        at org.spockframework.runtime.RunContext.stop(RunContext.java:67)
        at org.spockframework.runtime.RunContext.access$000(RunContext.java:30)
        at org.spockframework.runtime.RunContext$2.run(RunContext.java:159)
```

**Comment by user390181** [comment]
hello, any plans to address this issue in 'agent-java-spock'?  This reporting framework looks interesting but we cannot integrate it with our Spock test framework until this issue is resolved.

**Comment by dtanedo** [comment]
Hi,

I also encountered this error during testing.
```
[AppClassLoader@2a139a55] warning javax.* types are not being woven because the weaver option '-Xset:weaveJavaxPackages=true' has not been specified
Exception in thread "org.spockframework.runtime.RunContext.stop()" com.epam.reportportal.exception.ReportPortalClientException: Report Portal returned error
Status code: 404
Status message: Not Found
Error Message: Launch 'null' not found. Did you use correct Launch ID?
Error Type: LAUNCH_NOT_FOUND
Stack Trace: 
        at com.epam.reportportal.service.ReportPortalErrorHandler.handleClientError(ReportPortalErrorHandler.java:47)
        at com.epam.reportportal.restclient.endpoint.DefaultErrorHandler.handle(DefaultErrorHandler.java:73)
        at com.epam.reportportal.restclient.endpoint.DefaultErrorHandler.handle(DefaultErrorHandler.java:40)
        at com.epam.reportportal.restclient.endpoint.HttpClientRestEndpoint.executeInternal(HttpClientRestEndpoint.java:341)
        at com.epam.reportportal.restclient.endpoint.HttpClientRestEndpoint.put(HttpClientRestEndpoint.java:178)
        at com.epam.reportportal.service.ReportPortalService.finishLaunch(ReportPortalService.java:103)
        at com.epam.reportportal.spock.SpockReporter.finishLaunch(SpockReporter.java:300)
        at com.epam.reportportal.spock.ReportPortalSpockExtension.stop(ReportPortalSpockExtension.java:54)
        at org.spockframework.runtime.GlobalExtensionRegistry.stopGlobalExtensions(GlobalExtensionRegistry.java:112)
        at org.spockframework.runtime.RunContext.stop(RunContext.java:67)
        at org.spockframework.runtime.RunContext.access$000(RunContext.java:29)
        at org.spockframework.runtime.RunContext$2.run(RunContext.java:160)
```

**Comment by filland** [comment]
@dmikhievich Hello, could you look at the issue ?

**Comment by filland** [comment]
@greenleaves1  @dtanedo @user390181 checkout a new version of the agent for spock
https://bintray.com/beta/#/epam/reportportal/agent-java-spock?tab=overview
